version: '2.1'
services:
  mc:
    image: benton/spigot:0.5.0-1.11
    build:
      context: .
      dockerfile: src/spigot/Dockerfile
    volumes:
    - ./data:/data
    ports:
    - "25565:25565"
    depends_on:
    - spigot-build
  ssh:
    image: benton/ssh:0.1.6
    build:
      context: src/ssh
      args:
        DEFAULT_USER: mc
    volumes:
    - ./data:/data
  spigot-build:
    image: spigot-build
    depends_on:
    - java
    build:
      context: src/spigot-build
      args:
        SPIGOT_V: "1.11"
    volumes:
    - ./pkg:/pkg
  java:
    image: benton/java:8
    build:
      context: src/java
      args:
        JAVA_V: 8
