apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8craft
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: k8craft
    spec:
      containers:
      - name: mc
        image: benton/spigot:0.5.0-1.11
        env:
        - name: SERVER_JAR
          value: spigot
        - name: MAX_RAM
          value: 2560m
        ports:
        - containerPort: 25565
        volumeMounts:
        - name: k8craft-data
          mountPath: /data
        stdin: true
      - name: ssh
        image: benton/ssh:0.1.6
        env:
        - name: SSH_USER
          value: mc
        - name: SSH_KEY
          value: SSH_KEY_DATA
        ports:
        - containerPort: 22
        volumeMounts:
        - name: k8craft-data
          mountPath: /data
      volumes:
      - name: k8craft-data
        gcePersistentDisk:
          pdName: k8craft-data
          fsType: ext4
